name: motel
description: A new Flutter project.

version: 1.0.0+8

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.5.0
  path_provider: any
  bloc: ^4.0.0
  cached_network_image: 2.0.0-rc
  http: 0.12.0+2
  dio: 3.0.8
  cookie_jar: ^1.0.1
  shared_preferences: ^0.5.3+5
  ##shared_preferences: 0.5.6
  dio_cookie_manager: 1.0.0
  flushbar: 1.6.0
  simple_autocomplete_formfield: 0.2.4
  date_range_picker: ^1.0.5
  duration: 2.0.8
  select_dialog: ^1.0.7
  oktoast: 2.3.0
  smooth_star_rating: ^1.0.3
  flutter_page_indicator: ^0.0.3
  page_indicator: ^0.3.0
  intl: ^0.16.0
  rflutter_alert:
  webview_flutter: ^0.3.19+5
  flutter_datetime_picker: ^1.3.4
  uuid: ^2.0.4
  onesignal_flutter: ^2.0.0
  flutter_launcher_icons: "^0.7.3"
  flutter_localizations:
    sdk: flutter
  flutter_rounded_date_picker: 1.0.4
  google_fonts: ^0.3.10
  dotted_border: ^1.0.5
  flutter_typeahead: ^1.8.0
  datetime_picker_formfield: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/app_icon_android.png"


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - jsonFile/country_list.json
    - jsonFile/airline_codes.json
    - assets/images/editIcon.png
    - assets/images/dollar.png
    - assets/images/splash.png
    - assets/images/filter.png
    - assets/images/booking.png
    - assets/images/refresh.png
    - assets/images/logotype.png
    - assets/images/user.jpg
    - assets/images/add.png
    - assets/images/question.png
    - assets/images/originaline.png

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-ExtraBold.ttf 
        - asset: assets/fonts/Gilroy-Light.ttf 
        - asset: assets/fonts/Gilroy-Bold.ttf 
        - asset: assets/fonts/Gilroy-Medium.ttf          
        - asset: assets/fonts/Gilroy-SemiBold.ttf
          weight: 700

